"""cut_list_reconstruction.py - Build a 3D model from a cut list text file.

Parses a cutting list generated by the PlantBuilder driver and reconstructs
the 3D wafer geometry following 'Wafer Reconstruction.txt'.

Each wafer is built independently in its own local coordinate frame (cylinder
axis = Z, major-axis M = X) and then assembled by the mark-alignment rule:
  1. Face alignment  — orient entry face toward the exit face of the preceding wafer
  2. Center alignment — entry center coincides with the preceding exit center
  3. Mark alignment  — rotate about the shared face normal until marks coincide

No global coordinate system, frame chaining, or Cylinder° column is needed.

Entry point: reconstruct_and_visualize(App, Gui, filepath, max_wafers=None)
"""

import math

import FreeCAD as App
import Part

from wafer_loft import Wafer
from core.logging_setup import get_logger

logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Fractional inch parser
# ---------------------------------------------------------------------------

def _parse_fractional_inches(s: str) -> float:
    """Parse '1 3/8"' → 1.375, '3/4"' → 0.75, '2"' → 2.0, '0"' → 0.0."""
    s = s.strip().rstrip('"').strip()
    if not s:
        return 0.0
    parts = s.split()
    if not parts:
        return 0.0
    if '/' in parts[0]:
        num, den = parts[0].split('/')
        return int(num) / int(den)
    whole = int(parts[0])
    if len(parts) > 1 and '/' in parts[1]:
        num, den = parts[1].split('/')
        return whole + int(num) / int(den)
    return float(whole)


# ---------------------------------------------------------------------------
# Cut list parser
# ---------------------------------------------------------------------------

def parse_cut_list(filepath: str) -> list:
    """Parse a PlantBuilder cut list text file.

    Returns a list of segment dicts, one per SEGMENT: block::

        {
          'name': 'circle',
          'cylinder_diameter': 2.0,
          'initial_offset': 15.3,      # Cylinder° initial offset (not used for reconstruction)
          'rows': [
            {'cut': 1, 'length': 1.375, 'blade_deg': 2.5,
             'rot_deg': 0.0, 'cylinder_deg': 15.3},
            ...
          ]
        }
    """
    segments = []
    current_seg = None
    in_wafer_settings = False
    in_data_rows = False

    with open(filepath, 'r') as f:
        lines = f.readlines()

    for raw_line in lines:
        line = raw_line.rstrip('\n')
        stripped = line.strip()

        # ── New SEGMENT block ───────────────────────────────────────────
        if stripped.startswith('SEGMENT:'):
            if current_seg is not None:
                segments.append(current_seg)
            seg_name = stripped[len('SEGMENT:'):].strip()
            current_seg = {
                'name': seg_name,
                'cylinder_diameter': 2.0,
                'initial_offset': 0.0,
                'rows': [],
            }
            in_wafer_settings = False
            in_data_rows = False
            continue

        if current_seg is None:
            continue

        # ── Wafer settings block ────────────────────────────────────────
        if stripped == 'Wafer settings:':
            in_wafer_settings = True
            continue

        if in_wafer_settings:
            if stripped == '' or (line and not line[0].isspace()):
                in_wafer_settings = False
                # fall through so this line can be processed further
            else:
                if stripped.startswith('cylinder_diameter:'):
                    try:
                        val = stripped.split(':', 1)[1].strip()
                        current_seg['cylinder_diameter'] = float(val)
                    except (ValueError, IndexError):
                        pass
                continue

        # ── Initial offset ──────────────────────────────────────────────
        if 'Cylinder\u00b0 initial offset:' in stripped:
            try:
                val = stripped.split(':', 1)[1].strip().rstrip('\u00b0')
                current_seg['initial_offset'] = float(val)
            except (ValueError, IndexError):
                pass
            continue

        # ── Header row → start collecting data ─────────────────────────
        if (stripped.startswith('Cut') and 'Length' in stripped
                and 'Blade' in stripped):
            in_data_rows = True
            continue

        # ── End of data table ───────────────────────────────────────────
        if in_data_rows and stripped.startswith('Total cylinder length'):
            in_data_rows = False
            continue

        # ── All-dash separator ──────────────────────────────────────────
        if stripped and all(c == '-' for c in stripped):
            continue

        if not in_data_rows:
            continue

        # ── Parse data row ──────────────────────────────────────────────
        tokens = stripped.split()
        if not tokens:
            continue
        try:
            cut_num = int(tokens[0])
        except ValueError:
            continue

        # Length may span two tokens for mixed numbers like "1 3/8""
        idx = 1
        length_parts = []
        while idx < len(tokens):
            length_parts.append(tokens[idx])
            idx += 1
            if length_parts[-1].endswith('"'):
                break

        if not length_parts:
            logger.warning("Row %d: no length token found, skipping", cut_num)
            continue

        length_str = ' '.join(length_parts)
        length = _parse_fractional_inches(length_str)

        if idx + 2 >= len(tokens):
            logger.warning("Row %d: not enough tokens after length, skipping", cut_num)
            continue

        try:
            blade_deg    = float(tokens[idx])
            rot_deg      = float(tokens[idx + 1])
            cylinder_deg = float(tokens[idx + 2])
        except ValueError:
            logger.warning("Row %d: could not parse numeric columns, skipping", cut_num)
            continue

        current_seg['rows'].append({
            'cut':          cut_num,
            'length':       length,
            'blade_deg':    blade_deg,
            'rot_deg':      rot_deg,
            'cylinder_deg': cylinder_deg,
        })

    if current_seg is not None:
        segments.append(current_seg)

    logger.info("Parsed %d segment(s) from %s", len(segments), filepath)
    for seg in segments:
        logger.info("  Segment '%s': %d rows, diameter=%.3f",
                    seg['name'], len(seg['rows']), seg['cylinder_diameter'])

    return segments


# ---------------------------------------------------------------------------
# Geometry helpers
# ---------------------------------------------------------------------------

def _perp_to(v: App.Vector) -> App.Vector:
    """Return an arbitrary unit vector perpendicular to v."""
    v = App.Vector(v)
    v.normalize()
    candidate = App.Vector(1.0, 0.0, 0.0)
    if abs(v.dot(candidate)) > 0.9:
        candidate = App.Vector(0.0, 1.0, 0.0)
    result = v.cross(candidate)
    result.normalize()
    return result


def _build_rotation_from_frame(v1_l: App.Vector, v2_l: App.Vector,
                                v1_w: App.Vector, v2_w: App.Vector) -> App.Rotation:
    """Build the rotation R that maps v1_l → v1_w and v2_l → v2_w.

    v1_l and v2_l must be orthogonal unit vectors (local frame pair).
    v1_w and v2_w must be orthogonal unit vectors (world frame pair).
    The third axis is the right-hand cross product: v3 = v1 × v2.

    The rotation matrix elements satisfy:
        R[i][j] = sum_k  v{k}_w[i] * v{k}_l[j]
    """
    v3_l = v1_l.cross(v2_l)
    v3_w = v1_w.cross(v2_w)

    m = App.Matrix()
    m.A11 = v1_w.x * v1_l.x + v2_w.x * v2_l.x + v3_w.x * v3_l.x
    m.A12 = v1_w.x * v1_l.y + v2_w.x * v2_l.y + v3_w.x * v3_l.y
    m.A13 = v1_w.x * v1_l.z + v2_w.x * v2_l.z + v3_w.x * v3_l.z
    m.A21 = v1_w.y * v1_l.x + v2_w.y * v2_l.x + v3_w.y * v3_l.x
    m.A22 = v1_w.y * v1_l.y + v2_w.y * v2_l.y + v3_w.y * v3_l.y
    m.A23 = v1_w.y * v1_l.z + v2_w.y * v2_l.z + v3_w.y * v3_l.z
    m.A31 = v1_w.z * v1_l.x + v2_w.z * v2_l.x + v3_w.z * v3_l.x
    m.A32 = v1_w.z * v1_l.y + v2_w.z * v2_l.y + v3_w.z * v3_l.y
    m.A33 = v1_w.z * v1_l.z + v2_w.z * v2_l.z + v3_w.z * v3_l.z
    m.A44 = 1.0
    return App.Placement(m).Rotation


def _build_wafer_local(theta_entry_deg: float, theta_exit_deg: float,
                       rot_deg: float, L: float, radius: float):
    """Build a wafer solid in the wafer's local coordinate frame.

    Local frame convention (from 'Wafer Reconstruction.txt'):
        Cylinder axis = Z, entry face center at (0,0,0), exit at (0,0,L).
        Major-axis direction M = X = (1,0,0).
        M' = M rotated by rot_deg around Z.

    Cutting planes (spec outward normals):
        n_entry = −cos(θ_entry)·Z − sin(θ_entry)·M
        n_exit  =  cos(θ_exit)·Z  − sin(θ_exit)·M'

    The solid is a straight cylinder (axis Z) intersected with the two
    half-spaces.

    Returns (solid, plane1, plane2) where plane normals are stored as
    INWARD directions (T_entry, T_exit ≈ +Z) for compatibility with
    compare_reconstruction.  Returns (None, None, None) on failure.
    """
    te = math.radians(theta_entry_deg)
    tx = math.radians(theta_exit_deg)
    rot_rad = math.radians(rot_deg)

    # Spec outward normals
    n_entry_spec = App.Vector(-math.sin(te), 0.0, -math.cos(te))
    n_exit_spec  = App.Vector(
        -math.sin(tx) * math.cos(rot_rad),
        -math.sin(tx) * math.sin(rot_rad),
         math.cos(tx))

    # Cylinder must extend beyond both cutting planes
    tan_e = abs(math.tan(te)) if abs(te) < math.radians(89.9) else 1e6
    tan_x = abs(math.tan(tx)) if abs(tx) < math.radians(89.9) else 1e6
    extra_entry = radius * tan_e + radius
    extra_exit  = radius * tan_x + radius

    z_start    = -extra_entry
    cyl_height = L + extra_entry + extra_exit
    plane_size = radius * 100.0

    try:
        cylinder = Part.makeCylinder(
            radius, cyl_height,
            App.Vector(0.0, 0.0, z_start),
            App.Vector(0.0, 0.0, 1.0))

        # Cut away entry side: half-space on n_entry_spec side of z=0 plane
        c1 = Part.Circle(App.Vector(0, 0, 0), n_entry_spec, plane_size)
        f1 = Part.Face(Part.Wire([c1.toShape()]))
        hs1 = f1.extrude(n_entry_spec * plane_size)
        wafer = cylinder.cut(hs1)

        # Cut away exit side: half-space on n_exit_spec side of z=L plane
        c2 = Part.Circle(App.Vector(0, 0, L), n_exit_spec, plane_size)
        f2 = Part.Face(Part.Wire([c2.toShape()]))
        hs2 = f2.extrude(n_exit_spec * plane_size)
        wafer = wafer.cut(hs2)

        if wafer.ShapeType == 'Compound' and len(wafer.Solids) > 0:
            wafer = wafer.Solids[0]

        if not hasattr(wafer, 'Volume') or wafer.Volume < 1e-6:
            return None, None, None

    except Exception as exc:
        logger.error("_build_wafer_local error: %s", exc)
        return None, None, None

    # Inward normals (direction of travel) for Wafer plane dicts
    T_entry_l = App.Vector( math.sin(te), 0.0,  math.cos(te))
    T_exit_l  = App.Vector(
        -math.sin(tx) * math.cos(rot_rad),
        -math.sin(tx) * math.sin(rot_rad),
         math.cos(tx))

    plane1 = {'point': App.Vector(0.0, 0.0, 0.0), 'normal': T_entry_l}
    plane2 = {'point': App.Vector(0.0, 0.0, L),   'normal': T_exit_l}

    return wafer, plane1, plane2


# ---------------------------------------------------------------------------
# Segment reconstruction
# ---------------------------------------------------------------------------

def reconstruct_segment(segment_data: dict, max_wafers=None) -> list:
    """Reconstruct a list of Wafer objects from a parsed segment dict.

    Implements the mark-alignment assembly rule from 'Wafer Reconstruction.txt':
    each wafer is built in its own local frame and placed so that the entry
    mark coincides with the preceding wafer's exit mark.

    The placement of each wafer is determined by two orthonormal pairs:
        v1_l = n_entry_spec  (outward entry normal in local, ≈ −Z)
        v2_l = mark_dir_l    (direction entry center → entry mark in local)
    mapped to world targets:
        v1_w = −F_prev       (anti-parallel to preceding exit normal → face aligned)
        v2_w = mark_dir_prev (direction from preceding exit center to exit mark)

    All plane1/plane2 positions and normals are stored in the reconstruction's
    local frame (origin at the first wafer entry center, initial direction +Z).
    """
    radius = segment_data['cylinder_diameter'] / 2.0
    rows   = segment_data['rows']
    if max_wafers is not None:
        rows = rows[:max_wafers]
        logger.info("reconstruct_segment: limiting to first %d wafer(s)", max_wafers)

    wafers = []

    # ── Initial joint state (implicit flat-circle cut 0 for open curve) ──────
    # Starting position: origin.  Direction of travel: +Z.
    # Initial M direction: +X (arbitrary; determines global orientation).
    # Exit "mark" of the implicit cut 0 = origin + radius * M_dir = (R, 0, 0).
    joint_pos   = App.Vector(0.0, 0.0, 0.0)
    F_world     = App.Vector(0.0, 0.0, 1.0)   # outward exit normal of preceding cut
    mk_exit     = App.Vector(radius, 0.0, 0.0) # preceding exit mark position

    theta_entry_deg = 0.0   # blade angle of entry cut (0 = implicit flat circle)

    for i, row in enumerate(rows):
        theta_exit_deg = row['blade_deg']
        rot_deg        = row['rot_deg']
        L              = row['length']

        logger.info("── Wafer %d (cut #%d): entry_blade°=%.2f  exit_blade°=%.2f  "
                    "rot°=%.2f  len=%.4f",
                    i, row['cut'], theta_entry_deg, theta_exit_deg, rot_deg, L)

        # ── Build wafer solid in local frame ──────────────────────────────────
        solid_local, p1_l, p2_l = _build_wafer_local(
            theta_entry_deg, theta_exit_deg, rot_deg, L, radius)

        # ── Compute placement (mark-alignment assembly rule) ──────────────────
        te = math.radians(theta_entry_deg)

        # Local entry frame vectors (orthogonal pair, both unit):
        #   v1_l = spec outward entry normal = −cos(θ)·Z − sin(θ)·M
        #   v2_l = direction from entry center to entry mark (unit)
        #        = cos(θ)·M − sin(θ)·Z  = (cos(θ), 0, −sin(θ))
        v1_l = App.Vector(-math.sin(te), 0.0, -math.cos(te))
        v2_l = App.Vector( math.cos(te), 0.0, -math.sin(te))

        # World targets:
        #   v1_l must map to −F_world (face alignment)
        #   v2_l must map to normalize(mk_exit − joint_pos) (mark alignment)
        v1_w = App.Vector(-F_world.x, -F_world.y, -F_world.z)

        mk_dir = mk_exit - joint_pos
        if mk_dir.Length < 1e-9:
            mk_dir = _perp_to(F_world)
            logger.warning("  Wafer %d: degenerate mark direction — using fallback", i)
        else:
            mk_dir.normalize()
        v2_w = mk_dir

        rotation  = _build_rotation_from_frame(v1_l, v2_l, v1_w, v2_w)
        placement = App.Placement(joint_pos, rotation)

        logger.info("  Placement: origin=(%.4f,%.4f,%.4f)  "
                    "Z_world=(%.4f,%.4f,%.4f)  X_world=(%.4f,%.4f,%.4f)",
                    joint_pos.x, joint_pos.y, joint_pos.z,
                    rotation.multVec(App.Vector(0, 0, 1)).x,
                    rotation.multVec(App.Vector(0, 0, 1)).y,
                    rotation.multVec(App.Vector(0, 0, 1)).z,
                    rotation.multVec(App.Vector(1, 0, 0)).x,
                    rotation.multVec(App.Vector(1, 0, 0)).y,
                    rotation.multVec(App.Vector(1, 0, 0)).z)

        # ── Transform solid and planes to reconstruction local frame ──────────
        if solid_local is not None:
            solid_rec = solid_local.copy()
            solid_rec.transformShape(placement.toMatrix())

            p1_point = placement.multVec(p1_l['point'])
            p2_point = placement.multVec(p2_l['point'])
            p1_norm  = rotation.multVec(p1_l['normal'])
            p2_norm  = rotation.multVec(p2_l['normal'])

            plane1_rec = {'point': p1_point, 'normal': p1_norm}
            plane2_rec = {'point': p2_point, 'normal': p2_norm}

            geom = {
                'lift_angle_deg':    2.0 * theta_exit_deg,
                'rotation_angle_deg': rot_deg,
                'rotation_angle_rad': math.radians(rot_deg),
            }
            wafers.append(Wafer(solid_rec, i, plane1_rec, plane2_rec, geom))
            logger.info("  Wafer %d OK: volume=%.4f", i, solid_rec.Volume)
        else:
            logger.warning("  Wafer %d: degenerate geometry — solid skipped", i)

        # ── Advance joint state to exit of this wafer ─────────────────────────
        tx      = math.radians(theta_exit_deg)
        rot_rad = math.radians(rot_deg)

        # Exit center in reconstruction local frame
        joint_pos = placement.multVec(App.Vector(0.0, 0.0, L))

        # Exit face outward normal in local: n_exit = cos(θ)·Z − sin(θ)·M'
        n_exit_l = App.Vector(
            -math.sin(tx) * math.cos(rot_rad),
            -math.sin(tx) * math.sin(rot_rad),
             math.cos(tx))
        F_world = rotation.multVec(n_exit_l)

        # Exit mark in local: (R·cos(Rot°), R·sin(Rot°), L + R·tan(θ_exit))
        tan_x = math.tan(tx) if abs(tx) < math.radians(89.9) else 1e6
        mk_exit_l = App.Vector(
            radius * math.cos(rot_rad),
            radius * math.sin(rot_rad),
            L + radius * tan_x)
        mk_exit = placement.multVec(mk_exit_l)

        logger.info("  Joint: pos=(%.4f,%.4f,%.4f)  "
                    "F=(%.4f,%.4f,%.4f)",
                    joint_pos.x, joint_pos.y, joint_pos.z,
                    F_world.x, F_world.y, F_world.z)

        # Entry angle for next wafer = exit angle of this wafer
        theta_entry_deg = theta_exit_deg

    logger.info("Reconstructed %d wafers for segment '%s'",
                len(wafers), segment_data['name'])
    return wafers


# ---------------------------------------------------------------------------
# Alignment helpers
# ---------------------------------------------------------------------------

def _find_planar_faces(shape) -> list:
    """Return the planar faces of a wafer solid, sorted by area (largest first)."""
    planar = [face for face in shape.Faces
              if isinstance(face.Surface, Part.Plane)]
    planar.sort(key=lambda f: f.Area, reverse=True)
    return planar


def _face_normal(face) -> App.Vector:
    """Return the face's outward normal at the parameter-space midpoint."""
    try:
        pr = face.ParameterRange
        u = (pr[0] + pr[1]) * 0.5
        v = (pr[2] + pr[3]) * 0.5
        return face.normalAt(u, v)
    except Exception:
        return face.normalAt(0, 0)


def _find_original_alignment(doc, seg_name: str):
    """Compute a Placement that maps the reconstruction's local frame onto
    the original segment's first wafer entry face in the document.

    Returns App.Placement on success, or None if the original is not found.

    Strategy (priority order):
    1. LCS objects (LCS_{seg}_0_1): exact position and full rotation.
    2. Adjacent-wafer adjacency: exit face of wafer 0 is shared with wafer 1.
    3. Dot-product fallback when wafer 1 is absent.
    """
    candidates = doc.getObjectsByLabel(f"Wafer_{seg_name}_0")
    if not candidates:
        return None

    first_wafer_obj = candidates[0]
    shape = getattr(first_wafer_obj, 'Shape', None)
    if shape is None or shape.isNull():
        return None

    part_placement = App.Placement()
    part_candidates = doc.getObjectsByLabel(f"{seg_name}_Part")
    if part_candidates and hasattr(part_candidates[0], 'Placement'):
        part_placement = part_candidates[0].Placement

    # ── Priority 1: LCS (exact, full rotation) ───────────────────────────────
    lcs_candidates = doc.getObjectsByLabel(f"LCS_{seg_name}_0_1")
    if lcs_candidates and hasattr(lcs_candidates[0], 'Placement'):
        lcs_pl = lcs_candidates[0].Placement
        t_start = lcs_pl.Rotation.multVec(App.Vector(0, 0, 1))
        logger.info("Auto-align '%s' (LCS): entry=%s  T_start=%s",
                    seg_name, lcs_pl.Base, t_start)
        return lcs_pl

    # ── Fallback: face detection ──────────────────────────────────────────────
    planar = _find_planar_faces(shape)
    if len(planar) < 2:
        logger.warning("Could not find 2 planar faces in 'Wafer_%s_0'; "
                       "skipping auto-align", seg_name)
        return None

    fa, fb = planar[0], planar[1]
    c_a, c_b = fa.CenterOfMass, fb.CenterOfMass

    entry_face = None
    wafer1_cands = doc.getObjectsByLabel(f"Wafer_{seg_name}_1")
    if wafer1_cands:
        shape1 = getattr(wafer1_cands[0], 'Shape', None)
        if shape1 and not shape1.isNull():
            planar1 = _find_planar_faces(shape1)
            if planar1:
                w1_centers = [f.CenterOfMass for f in planar1]
                dist_a = min((c_a - c1).Length for c1 in w1_centers)
                dist_b = min((c_b - c1).Length for c1 in w1_centers)
                exit_face  = fa if dist_a < dist_b else fb
                entry_face = fb if dist_a < dist_b else fa
                logger.info("Auto-align '%s': exit↔wafer1 dist_a=%.4f dist_b=%.4f",
                            seg_name, dist_a, dist_b)

    if entry_face is None:
        chord_local = c_b - c_a
        if chord_local.Length < 1e-9:
            return None
        chord_local.normalize()
        n_a = _face_normal(fa)
        entry_face = fa if n_a.dot(chord_local) < 0 else fb
        logger.info("Auto-align '%s': using dot-product fallback", seg_name)

    local_center = entry_face.CenterOfMass
    local_n_out  = _face_normal(entry_face)
    local_n_out.normalize()

    world_center = part_placement.multVec(local_center)
    world_n_out  = part_placement.Rotation.multVec(local_n_out)

    t_start = App.Vector(-world_n_out.x, -world_n_out.y, -world_n_out.z)
    t_start.normalize()

    z_axis = App.Vector(0, 0, 1)
    dot = max(-1.0, min(1.0, t_start.dot(z_axis)))
    if dot > 1.0 - 1e-9:
        rotation = App.Rotation()
    elif dot < -1.0 + 1e-9:
        rotation = App.Rotation(App.Vector(1, 0, 0), 180.0)
    else:
        rotation = App.Rotation(z_axis, t_start)

    placement = App.Placement(world_center, rotation)
    logger.info("Auto-align '%s' (faces): entry=%s  T_start=%s",
                seg_name, world_center, t_start)
    return placement


# ---------------------------------------------------------------------------
# Diagnostic comparison helpers
# ---------------------------------------------------------------------------

def _get_part_placement(doc, part_label: str):
    """Return the Placement of a Part object, or identity if not found."""
    candidates = doc.getObjectsByLabel(part_label)
    if candidates and hasattr(candidates[0], 'Placement'):
        return candidates[0].Placement
    return App.Placement()


def _extract_wafer_params(shape, part_placement):
    """Extract blade°, chord_length, and world-space entry centre from a shape."""
    planar = _find_planar_faces(shape)
    if len(planar) < 2:
        return None

    face_a, face_b = planar[0], planar[1]
    c_a = face_a.CenterOfMass
    c_b = face_b.CenterOfMass
    chord_local = c_b - c_a
    if chord_local.Length < 1e-9:
        return None
    chord_norm = App.Vector(chord_local)
    chord_norm.normalize()

    n_a = _face_normal(face_a)
    if n_a.dot(chord_norm) < 0:
        entry_face, exit_face = face_a, face_b
    else:
        entry_face, exit_face = face_b, face_a

    t_entry = App.Vector(-_face_normal(entry_face).x,
                         -_face_normal(entry_face).y,
                         -_face_normal(entry_face).z)
    t_exit  = _face_normal(exit_face)
    dot = max(-1.0, min(1.0, t_entry.dot(t_exit)))
    lift_angle_deg = math.degrees(math.acos(dot))

    entry_world = part_placement.multVec(entry_face.CenterOfMass)

    return {
        'blade_deg':    lift_angle_deg / 2.0,
        'chord_length': chord_local.Length,
        'entry_world':  entry_world,
    }


def compare_reconstruction(doc, seg_name: str, rows: list = None,
                           rec_wafers=None, alignment=None):
    """Log a per-wafer comparison table between original build and reconstruction.

    Columns: Cut, Rot°, Bld°CL, Bld°Or, Bld°Re, Len CL, Len Or, Len Re,
             PosErr, Δx, Δy, Δz.

    rec_wafers: Wafer list from reconstruct_segment (plane1/plane2 in
                reconstruction local frame).
    alignment:  Placement mapping reconstruction local → world.
    """
    orig_placement = _get_part_placement(doc, f"{seg_name}_Part")
    rec_wafer_dict = {w.index: w for w in rec_wafers} if rec_wafers else {}
    align = alignment if alignment is not None else App.Placement()

    hdr = (f"{'Cut':>4}  {'Rot°':>7}  "
           f"{'Bld°CL':>7}  {'Bld°Or':>7}  {'Bld°Re':>7}  "
           f"{'Len CL':>7}  {'Len Or':>7}  {'Len Re':>7}  "
           f"{'PosErr':>7}  {'Δx':>8}  {'Δy':>8}  {'Δz':>8}")
    logger.info("=== Wafer comparison: %s ===", seg_name)
    logger.info(hdr)
    logger.info("-" * len(hdr))

    i = 0
    while True:
        orig_objs = doc.getObjectsByLabel(f"Wafer_{seg_name}_{i}")
        rec_objs  = doc.getObjectsByLabel(f"Wafer_{seg_name}_Rec_{i}")
        has_rec   = bool(rec_objs) or (i in rec_wafer_dict)

        if not orig_objs and not has_rec:
            break

        cl_row = rows[i] if (rows and i < len(rows)) else None

        orig_params = None
        if orig_objs:
            shp = getattr(orig_objs[0], 'Shape', None)
            if shp and not shp.isNull():
                orig_params = _extract_wafer_params(shp, orig_placement)

        if orig_params is not None:
            lcs_cands = doc.getObjectsByLabel(f"LCS_{seg_name}_{i}_1")
            if lcs_cands and hasattr(lcs_cands[0], 'Placement'):
                orig_params['entry_world'] = lcs_cands[0].Placement.Base

        rec_params = None
        if i in rec_wafer_dict:
            w = rec_wafer_dict[i]
            T_entry = w.plane1['normal']
            T_exit  = w.plane2['normal']
            dot = max(-1.0, min(1.0, T_entry.dot(T_exit)))
            lift_angle_deg = math.degrees(math.acos(dot))
            chord_len = (w.plane2['point'] - w.plane1['point']).Length
            entry_world = align.multVec(w.plane1['point'])
            rec_params = {
                'blade_deg':    lift_angle_deg / 2.0,
                'chord_length': chord_len,
                'entry_world':  entry_world,
            }
        elif rec_objs:
            rec_placement = _get_part_placement(doc, f"{seg_name}_Reconstructed")
            shp = getattr(rec_objs[0], 'Shape', None)
            if shp and not shp.isNull():
                rec_params = _extract_wafer_params(shp, rec_placement)

        pos_err = None
        dx = dy = dz = None
        if orig_params and rec_params:
            diff = orig_params['entry_world'] - rec_params['entry_world']
            pos_err = diff.Length
            dx, dy, dz = diff.x, diff.y, diff.z

        rot_cl  = f"{cl_row['rot_deg']:+7.1f}"  if cl_row       else "      -"
        bld_cl  = f"{cl_row['blade_deg']:7.2f}"  if cl_row       else "      -"
        len_cl  = f"{cl_row['length']:7.4f}"     if cl_row       else "      -"
        bld_or  = f"{orig_params['blade_deg']:7.2f}"    if orig_params else "      -"
        bld_re  = f"{rec_params['blade_deg']:7.2f}"     if rec_params  else "      -"
        len_or  = f"{orig_params['chord_length']:7.4f}" if orig_params else "      -"
        len_re  = f"{rec_params['chord_length']:7.4f}"  if rec_params  else "      -"
        pos_str = f"{pos_err:7.4f}"              if pos_err is not None else "      -"
        dx_str  = f"{dx:+8.4f}"                  if dx is not None else "       -"
        dy_str  = f"{dy:+8.4f}"                  if dy is not None else "       -"
        dz_str  = f"{dz:+8.4f}"                  if dz is not None else "       -"

        logger.info("%4d  %s  %s  %s  %s  %s  %s  %s  %s  %s  %s  %s",
                    i + 1,
                    rot_cl, bld_cl, bld_or, bld_re,
                    len_cl, len_or, len_re,
                    pos_str, dx_str, dy_str, dz_str)
        i += 1

    logger.info("--- Total wafers compared: %d ---", i)


# ---------------------------------------------------------------------------
# FreeCAD visualization
# ---------------------------------------------------------------------------

def visualize_reconstruction(doc, seg_name: str, wafers: list,
                             placement=None):
    """Create FreeCAD visualization of reconstructed wafers.

    Tree structure::

        {seg_name}_Reconstructed    (App::Part)
        └── {seg_name}_Rec_Wafers   (App::DocumentObjectGroup)
            ├── Wafer_{seg_name}_Rec_0  (Part::Feature)  ← orange
            ├── Wafer_{seg_name}_Rec_1                   ← amber
            └── ...

    placement: if the original is found, the Part is placed to overlay it
               (50% transparent); otherwise offset +200mm in X.
    """
    part_name  = f"{seg_name}_Reconstructed"
    group_name = f"{seg_name}_Rec_Wafers"

    seg_part = doc.addObject("App::Part", part_name)
    aligned = placement is not None
    seg_part.Placement = (placement if aligned
                          else App.Placement(App.Vector(200, 0, 0),
                                            App.Rotation()))

    wafer_group = doc.addObject("App::DocumentObjectGroup", group_name)
    transparency = 50 if aligned else 0

    wafer_count = 0
    for wafer_obj in wafers:
        if wafer_obj.wafer is None:
            continue

        obj_name = f"Wafer_{seg_name}_Rec_{wafer_obj.index}"
        feat = doc.addObject("Part::Feature", obj_name)
        feat.Shape = wafer_obj.wafer

        if wafer_obj.index % 2 == 0:
            feat.ViewObject.ShapeColor = (1.0, 0.6, 0.2)
        else:
            feat.ViewObject.ShapeColor = (1.0, 0.85, 0.4)

        feat.ViewObject.Transparency = transparency
        wafer_group.addObject(feat)
        wafer_count += 1

    seg_part.addObject(wafer_group)
    doc.recompute()

    if aligned:
        logger.info("Visualization: %d wafers in '%s' (aligned, 50%% transparent)",
                    wafer_count, part_name)
    else:
        logger.info("Visualization: %d wafers in '%s' (+200mm X fallback)",
                    wafer_count, part_name)
    return seg_part


# ---------------------------------------------------------------------------
# Debug plane visualization
# ---------------------------------------------------------------------------

def _add_debug_planes(doc, seg_name: str, cylinder_radius: float,
                      orig_placement, rec_placement):
    """Add thin-disc markers at entry/exit planes of the first wafer pair.

    4 discs: bright red = orig entry, dark red = orig exit,
             bright green = rec entry, dark green = rec exit.
    """
    disc_radius = cylinder_radius * 1.5
    disc_height = 0.05

    def _extract_entry_exit(shape, placement):
        planar = _find_planar_faces(shape)
        if len(planar) < 2:
            return None
        fa, fb = planar[0], planar[1]
        chord_local = fb.CenterOfMass - fa.CenterOfMass
        if chord_local.Length < 1e-9:
            return None
        chord_local.normalize()
        n_a = _face_normal(fa)
        entry_face = fa if n_a.dot(chord_local) < 0 else fb
        exit_face  = fb if n_a.dot(chord_local) < 0 else fa

        entry_c = placement.multVec(entry_face.CenterOfMass)
        entry_n = placement.Rotation.multVec(_face_normal(entry_face))
        entry_n.normalize()
        exit_c  = placement.multVec(exit_face.CenterOfMass)
        exit_n  = placement.Rotation.multVec(_face_normal(exit_face))
        exit_n.normalize()
        return entry_c, entry_n, exit_c, exit_n

    def _make_disc(center_world, normal_world, color, name):
        half_h = disc_height * 0.5
        base = App.Vector(center_world.x - normal_world.x * half_h,
                          center_world.y - normal_world.y * half_h,
                          center_world.z - normal_world.z * half_h)
        try:
            disc = Part.makeCylinder(disc_radius, disc_height, base, normal_world)
        except Exception as exc:
            logger.warning("_make_disc '%s': %s", name, exc)
            return None
        feat = doc.addObject("Part::Feature", name)
        feat.Shape = disc
        feat.ViewObject.ShapeColor = color
        feat.ViewObject.Transparency = 20
        return feat

    group = doc.addObject("App::DocumentObjectGroup", f"{seg_name}_DebugPlanes")

    orig_objs = doc.getObjectsByLabel(f"Wafer_{seg_name}_0")
    if orig_objs:
        shp = getattr(orig_objs[0], 'Shape', None)
        if shp and not shp.isNull():
            result = _extract_entry_exit(shp, orig_placement)
            if result:
                e_c, e_n, x_c, x_n = result
                f1 = _make_disc(e_c, e_n, (1.0, 0.2, 0.2), f"{seg_name}_Orig_Entry")
                f2 = _make_disc(x_c, x_n, (0.6, 0.0, 0.0), f"{seg_name}_Orig_Exit")
                if f1: group.addObject(f1)
                if f2: group.addObject(f2)
                logger.info("Orig wafer 0 entry: center=%s  n=%s", e_c, e_n)
                logger.info("Orig wafer 0 exit:  center=%s  n=%s", x_c, x_n)

    rec_objs = doc.getObjectsByLabel(f"Wafer_{seg_name}_Rec_0")
    if rec_objs:
        shp = getattr(rec_objs[0], 'Shape', None)
        if shp and not shp.isNull():
            result = _extract_entry_exit(shp, rec_placement)
            if result:
                e_c, e_n, x_c, x_n = result
                f1 = _make_disc(e_c, e_n, (0.2, 1.0, 0.2), f"{seg_name}_Rec_Entry")
                f2 = _make_disc(x_c, x_n, (0.0, 0.6, 0.0), f"{seg_name}_Rec_Exit")
                if f1: group.addObject(f1)
                if f2: group.addObject(f2)
                logger.info("Rec  wafer 0 entry: center=%s  n=%s", e_c, e_n)
                logger.info("Rec  wafer 0 exit:  center=%s  n=%s", x_c, x_n)

    doc.recompute()
    logger.info("Debug planes added to '%s_DebugPlanes'", seg_name)


# ---------------------------------------------------------------------------
# Top-level entry point (called from the task panel)
# ---------------------------------------------------------------------------

def reconstruct_and_visualize(App, Gui, filepath: str, max_wafers: int = None):
    """Parse a cut list file and reconstruct all segments in the active doc.

    Reconstruction follows 'Wafer Reconstruction.txt': each wafer is built
    independently in its local frame and assembled by mark-alignment.

    If the original segment is found in the document, the reconstruction
    is auto-aligned to overlay it (50% transparent orange/amber).  Otherwise
    the reconstruction is placed +200mm in X.

    Parameters
    ----------
    max_wafers : int or None
        Limit reconstruction to the first N wafers.  When set, debug plane
        markers are also added at the first wafer's entry/exit planes.
    """
    doc = App.activeDocument()
    if doc is None:
        doc = App.newDocument("Reconstruction")

    segments = parse_cut_list(filepath)
    if not segments:
        raise ValueError(f"No segments found in: {filepath}")

    for seg_data in segments:
        alignment = _find_original_alignment(doc, seg_data['name'])
        if alignment is None:
            logger.info("Segment '%s': original not found — +200mm X fallback",
                        seg_data['name'])

        wafers = reconstruct_segment(seg_data, max_wafers=max_wafers)

        rec_part = visualize_reconstruction(
            doc, seg_data['name'], wafers, alignment)

        if max_wafers is not None and max_wafers <= 5:
            radius = seg_data['cylinder_diameter'] / 2.0
            orig_placement = _get_part_placement(doc, f"{seg_data['name']}_Part")
            rec_placement  = (rec_part.Placement if rec_part is not None
                              else App.Placement())
            _add_debug_planes(doc, seg_data['name'], radius,
                              orig_placement, rec_placement)

        compare_reconstruction(doc, seg_data['name'], seg_data.get('rows'),
                               rec_wafers=wafers, alignment=alignment)

    if Gui is not None:
        try:
            Gui.SendMsgToActiveView("ViewFit")
        except Exception:
            pass

    doc.recompute()
    logger.info("Reconstruction complete: %d segment(s) from %s",
                len(segments), filepath)
